#!/usr/bin/env python3
"""Generate res/controllers/Hercules DJControl Mix Ultra.midi.xml from the
captured MIDI layout (testing/results/2026-10-08_mix-ultra.md).

    python3 tools/controller/gen_mix_ultra_xml.py
"""

from pathlib import Path
from xml.sax.saxutils import escape

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "res" / "controllers" / "Hercules DJControl Mix Ultra.midi.xml"

controls = []


def script(group, function, status, midino, comment):
    controls.append((comment, group, f"MixUltra.{function}", status, midino, "<script-binding/>"))


def fourteen_bit(group, key, status, msb, comment, extra=""):
    controls.append((comment + " (MSB)", group, key, status, msb, f"<fourteen-bit-msb/>{extra}"))
    controls.append((comment + " (LSB)", group, key, status, msb + 0x20, f"<fourteen-bit-lsb/>{extra}"))


# Global
fourteen_bit("[Master]", "crossfader", 0xB0, 0x00, "Crossfader")
fourteen_bit("[Master]", "gain", 0xB0, 0x03, "Master volume")
script("[Library]", "browse", 0xB0, 0x01, "Browser turn")
script("[Library]", "shiftBrowse", 0xB3, 0x01, "Browser turn + SHIFT")
script("[Library]", "browsePress", 0x90, 0x00, "Browser press")
script("[Library]", "shiftBrowsePress", 0x93, 0x00, "Browser press + SHIFT")
script("[Skin]", "stems", 0x90, 0x01, "STEMS (centre button)")
script("[Skin]", "shiftStems", 0x93, 0x01, "STEMS + SHIFT: beat lights on/off")

for deck in (1, 2):
    g = f"[Channel{deck}]"
    note = 0x90 + deck
    cc = 0xB0 + deck
    snote = 0x93 + deck
    scc = 0xB3 + deck
    pads = 0x95 + deck
    d = f"Deck {deck}"
    script(g, "shiftButton", note, 0x04, f"{d} SHIFT")
    script(g, "sync", note, 0x05, f"{d} SYNC")
    script(g, "shiftSync", snote, 0x05, f"{d} SYNC + SHIFT: keylock")
    script(g, "cue", note, 0x06, f"{d} CUE")
    script(g, "shiftCue", snote, 0x06, f"{d} CUE + SHIFT: back to start, stop")
    script(g, "play", note, 0x07, f"{d} PLAY")
    script(g, "shiftPlay", snote, 0x07, f"{d} PLAY + SHIFT: stutter")
    script(g, "jogTouch", note, 0x08, f"{d} jog touch")
    script(g, "jogTouch", snote, 0x08, f"{d} jog touch + SHIFT")
    script(g, "pfl", note, 0x0C, f"{d} headphones (PFL)")
    script(g, "shiftPfl", snote, 0x0C, f"{d} headphones + SHIFT: quantize")
    script(g, "load", note, 0x0D, f"{d} LOAD")
    script(g, "shiftLoad", snote, 0x0D, f"{d} LOAD + SHIFT: eject")
    for midino, name in ((0x0F, "HOT CUE"), (0x10, "LOOP"), (0x11, "FX"), (0x12, "NEURAL MIX"),
                         (0x13, "PITCH PLAY"), (0x14, "BOUNCE LOOP"), (0x15, "SLICER"),
                         (0x16, "SAMPLER")):
        script(g, "modeButton", note, midino, f"{d} mode {name}")
    script(g, "jogTop", cc, 0x0A, f"{d} jog top")
    script(g, "jogRing", cc, 0x09, f"{d} jog ring")
    script(g, "jogSeek", scc, 0x0A, f"{d} jog top + SHIFT: seek")
    script(g, "jogRing", scc, 0x09, f"{d} jog ring + SHIFT")
    fourteen_bit(g, "volume", cc, 0x00, f"{d} volume fader")
    fourteen_bit(f"[QuickEffectRack1_{g}]", "super1", cc, 0x01, f"{d} filter")
    fourteen_bit(f"[EqualizerRack1_{g}_Effect1]", "parameter1", cc, 0x02, f"{d} EQ low")
    fourteen_bit(f"[EqualizerRack1_{g}_Effect1]", "parameter2", cc, 0x03, f"{d} EQ mid")
    fourteen_bit(f"[EqualizerRack1_{g}_Effect1]", "parameter3", cc, 0x04, f"{d} EQ high")
    fourteen_bit(g, "pregain", scc, 0x04, f"{d} gain (SHIFT + EQ high)")
    fourteen_bit(g, "rate", cc, 0x08, f"{d} tempo fader", "<soft-takeover/>")
    for midino in range(0x80):
        script(g, "pad", pads, midino, f"{d} pad {(midino & 7) + 1} ({midino:02X})")


def main():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by tools/controller/gen_mix_ultra_xml.py: edit that, not this file. -->",
        '<MixxxMIDIPreset mixxxVersion="2.5" schemaVersion="1">',
        "    <info>",
        "        <name>Hercules DJControl Mix Ultra</name>",
        "        <author>DJ Mantra</author>",
        "        <description>Hercules DJControl Mix Ultra over USB or Bluetooth LE MIDI. "
        "Written from a capture of the real controller. Beat lights: the pads show the "
        "position in the 8-beat phrase in every pad mode (SHIFT + STEMS turns them off)."
        "</description>",
        "        <devices>",
        '            <product protocol="midi" vendor_id="0x06f8" product_id="0xb131"/>',
        "        </devices>",
        "    </info>",
        '    <controller id="DJControl Mix Ultra">',
        "        <scriptfiles>",
        '            <file functionprefix="MixUltra" filename="Hercules-DJControl-Mix-Ultra-script.js"/>',
        "        </scriptfiles>",
        "        <controls>",
    ]
    for comment, group, key, status, midino, options in controls:
        lines += [
            f"            <!-- {escape(comment)} -->",
            "            <control>",
            f"                <group>{escape(group)}</group>",
            f"                <key>{escape(key)}</key>",
            f"                <status>0x{status:02X}</status>",
            f"                <midino>0x{midino:02X}</midino>",
            f"                <options>{options}</options>",
            "            </control>",
        ]
    lines += ["        </controls>", "        <outputs/>", "    </controller>", "</MixxxMIDIPreset>", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(controls)} controls)")


if __name__ == "__main__":
    main()
