#!/usr/bin/env python3
"""Generates DJ Mantra's launcher icon: the vertical waveform view (as djay's
portrait waveform view, docs/ui-reference/pixel7-portrait-waveform-*.png)
filling the whole circle: deck 1 and deck 2 as two vertical "spines" of
thin horizontal slices in spectral colours (red bass, green/cyan mids,
blue/purple highs), grey beat lines and the red playhead across both.

Writes the Android adaptive icon (vector drawables, API 26+) into
packaging/android/package/res and, with --preview FILE.png, a PNG preview.
Deterministic: the same output on every run.
"""
import argparse
import colorsys
import math
import os
import random

BACKGROUND = "#000000"
PLAYHEAD = "#FF2A2A"
BEATLINE = "#4A4A50"
DIVIDER = "#3A3A3E"

# The whole 108 dp canvas is drawn: the launcher's mask (circle, squircle)
# cuts it, so the waveforms reach the edge of the icon
SIZE = 108.0
SLICE, STEP = 0.5, 0.85
CENTERS = (36.5, 71.5)
MAX_HALF = 15.0
PLAYHEAD_Y = 51.0
BEAT_STEP = (12.0, 9.0)   # deck 2 is faster: closer beat lines


def envelope(deck, y):
    """Loudness 0..1 and the slice's colour band along the track (top to
    bottom): "blue" (highs), "mid" (green/cyan), "bass" (red)."""
    t = (y - 18.0) / 72.0          # 0..1 over the part the launcher shows
    if deck == 0:
        loud = 0.35 + 0.45 * min(max(t, 0.0), 1.0) + 0.2 * math.sin(t * 10.0) ** 2
        band = "blue" if t < 0.2 else ("mid" if t < 0.62 else "bass")
    else:
        wave = abs(math.sin(t * 8.0 + 0.4))
        loud = 0.35 + 0.6 * wave
        band = "bass" if wave > 0.45 else ("magenta" if wave > 0.25 else "mid")
    return min(loud, 1.0), band


PALETTE = {
    "blue": ["#3355FF", "#5533EE", "#7744FF", "#2277FF"],
    "mid": ["#22DD88", "#22CCCC", "#33EE55", "#44BBEE"],
    "bass": ["#FF2222", "#FF3311", "#EE1144", "#FF5522"],
    "magenta": ["#CC33DD", "#9944FF", "#EE33AA"],
}


def spectral(band, rnd):
    """A slice colour from its band, with streaks of the other bands now and
    then, as in djay's spectral waveform."""
    r = rnd.random()
    if r < 0.12:
        band = rnd.choice(["blue", "mid", "magenta"])
    elif r < 0.18:
        band = "bass"
    return rnd.choice(PALETTE[band])


def slices(deck):
    rnd = random.Random(deck + 7)
    out = []
    y = 0.2
    while y < SIZE:
        loud, band = envelope(deck, y)
        beat = abs(math.sin(y * math.pi / BEAT_STEP[deck]))
        # jagged edge: every slice its own width
        half = MAX_HALF * loud * (0.6 + 0.4 * beat) * (0.55 + 0.45 * rnd.random())
        half = max(half, 1.2)
        out.append((y, half, spectral(band, rnd)))
        # high-frequency fringe: a thin, wider, darker slice now and then
        if rnd.random() < 0.3:
            out.append((y + SLICE * 0.5, half * (1.1 + 0.3 * rnd.random()), "#5A3A8A"))
        y += STEP
    return out


def shapes():
    """(color, x, y, w, h) rectangles, back to front."""
    rects = []
    for deck, cx in enumerate(CENTERS):
        y = (PLAYHEAD_Y % BEAT_STEP[deck]) - BEAT_STEP[deck]
        while y < SIZE:
            x0 = 54.6 if deck else 0.0
            rects.append((BEATLINE, x0, y, 53.4, 0.3))
            y += BEAT_STEP[deck]
        fringe = [s for s in slices(deck) if s[2] == "#5A3A8A"]
        body = [s for s in slices(deck) if s[2] != "#5A3A8A"]
        for y, half, color in fringe + body:
            h = SLICE * (0.6 if color == "#5A3A8A" else 1.0)
            rects.append((color, cx - half, y, 2 * half, h))
    rects.append((DIVIDER, 53.75, 0.0, 0.5, SIZE))
    rects.append((PLAYHEAD, 0.0, PLAYHEAD_Y, SIZE, 0.7))
    return rects


def vector_foreground():
    paths = []
    for color, x, y, w, h in shapes():
        d = f"M{x:.2f},{y:.2f}h{w:.2f}v{h:.2f}h{-w:.2f}z"
        if paths and paths[-1][0] == color:
            paths[-1][1].append(d)
        else:
            paths.append((color, [d]))
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/android/gen_launcher_icon.py -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="108dp" android:height="108dp"',
           '    android:viewportWidth="108" android:viewportHeight="108">']
    for color, parts in paths:
        out.append(f'    <path android:fillColor="{color}" android:pathData="{"".join(parts)}"/>')
    out.append('</vector>')
    return "\n".join(out) + "\n"


def svg_icon():
    """The icon as the launcher shows it (the middle 72 of 108 dp, in a
    circle): the app's start screen shows it (res/skins/DJMantra)."""
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" '
           'width="288" height="288">',
           '<!-- Generated by tools/android/gen_launcher_icon.py -->',
           '<defs><clipPath id="c"><circle cx="54" cy="54" r="36"/></clipPath></defs>',
           '<g clip-path="url(#c)">',
           f'<rect x="18" y="18" width="72" height="72" fill="{BACKGROUND}"/>']
    for color, x, y, w, h in shapes():
        out.append(f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" '
                   f'fill="{color}"/>')
    out.append('</g></svg>')
    return "\n".join(out) + "\n"


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
"""

COLORS_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
"""


def preview(path, size=432):
    from PIL import Image, ImageDraw
    scale = size / SIZE
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).ellipse((0, 0, size - 1, size - 1), fill=255)
    canvas = Image.new("RGBA", (size, size), BACKGROUND)
    draw = ImageDraw.Draw(canvas)
    for color, x, y, w, h in shapes():
        draw.rectangle((x * scale, y * scale, (x + w) * scale, (y + h) * scale), fill=color)
    # the launcher shows about the middle 72 of 108 dp: preview that part
    crop = int(18 * scale)
    canvas = canvas.crop((crop, crop, size - crop, size - crop)).resize((size, size))
    img.paste(canvas, (0, 0), mask)
    img.save(path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview")
    args = parser.parse_args()
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..",
                        "packaging", "android", "package", "res")
    files = {
        "drawable/ic_launcher_foreground.xml": vector_foreground(),
        "mipmap-anydpi-v26/ic_launcher.xml": ADAPTIVE,
        "mipmap-anydpi-v26/ic_launcher_round.xml": ADAPTIVE,
        "values/ic_launcher_colors.xml": COLORS_XML,
    }
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
    if args.preview:
        preview(args.preview)


if __name__ == "__main__":
    main()
