#!/usr/bin/env python3
"""Generates DJ Mantra's launcher icon: two waveforms, one above the other
(deck 1 on top, deck 2 below, like the immersive waveform view), colored by
song section, with a white playhead across both.

Writes the Android adaptive icon (vector drawables, API 26+) into
packaging/android/package/res and, with --preview FILE.png, a PNG preview.
Deterministic: the same output on every run.
"""
import argparse
import math
import os
import random

BACKGROUND = "#0D0A1E"
PLAYHEAD = "#FFFFFF"
# Section colors (djay-style section palette)
COLORS = {
    "intro": "#3D7BFF",
    "build": "#22D3EE",
    "drop": "#FF3D6E",
    "break": "#A855F7",
    "drop2": "#FF8A1F",
    "outro": "#2BD47D",
}
# (section, share of the width, loudness 0..1)
DECK1 = [("intro", 0.16, 0.35), ("build", 0.18, 0.6), ("drop", 0.26, 1.0),
         ("break", 0.14, 0.4), ("drop2", 0.26, 0.95)]
DECK2 = [("break", 0.14, 0.4), ("drop2", 0.28, 0.95), ("build", 0.16, 0.6),
         ("drop", 0.24, 1.0), ("outro", 0.18, 0.4)]

# Adaptive icon: 108x108 canvas, everything inside the 66 dp safe zone
X0, X1 = 21.0, 87.0
BAR, GAP = 1.3, 0.6
DECK_CENTERS = (42.0, 66.0)
MAX_HALF = 10.5


def bars(sections, seed):
    rnd = random.Random(seed)
    n = int((X1 - X0 + GAP) / (BAR + GAP))
    total = sum(share for _, share, _ in sections)
    edges = []
    acc = 0.0
    for name, share, loud in sections:
        edges.append((acc / total, (acc + share) / total, name, loud))
        acc += share
    result = []
    for i in range(n):
        t = (i + 0.5) / n
        for start, end, name, loud in edges:
            if start <= t < end or (t >= end and end == 1.0):
                break
        # Beat-like pulse plus noise, scaled by the section's loudness
        pulse = 0.65 + 0.35 * abs(math.sin(i * 1.7))
        h = MAX_HALF * loud * pulse * (0.75 + 0.25 * rnd.random())
        h = max(h, 1.2)
        result.append((X0 + i * (BAR + GAP), h, COLORS[name]))
    return result


def vector_foreground():
    paths = {}
    for deck, (sections, cy) in enumerate(zip((DECK1, DECK2), DECK_CENTERS)):
        for x, h, color in bars(sections, seed=deck + 1):
            paths.setdefault(color, []).append(
                f"M{x:.2f},{cy - h:.2f}h{BAR}v{2 * h:.2f}h-{BAR}z")
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/android/gen_launcher_icon.py -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="108dp" android:height="108dp"',
           '    android:viewportWidth="108" android:viewportHeight="108">']
    for color, parts in paths.items():
        out.append(f'    <path android:fillColor="{color}" android:pathData="{"".join(parts)}"/>')
    # Playhead
    out.append(f'    <path android:fillColor="{PLAYHEAD}" '
               f'android:pathData="M53.4,28h1.2v52h-1.2z"/>')
    out.append('</vector>')
    return "\n".join(out) + "\n"


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
"""

COLORS_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
"""


def preview(path, size=432):
    from PIL import Image, ImageDraw
    scale = size / 108.0
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).ellipse((0, 0, size - 1, size - 1), fill=255)
    canvas = Image.new("RGBA", (size, size), BACKGROUND)
    draw = ImageDraw.Draw(canvas)
    for deck, (sections, cy) in enumerate(zip((DECK1, DECK2), DECK_CENTERS)):
        for x, h, color in bars(sections, seed=deck + 1):
            draw.rectangle((x * scale, (cy - h) * scale,
                            (x + BAR) * scale - 1, (cy + h) * scale), fill=color)
    draw.rectangle((53.4 * scale, 28 * scale, 54.6 * scale, 80 * scale), fill=PLAYHEAD)
    img.paste(canvas, (0, 0), mask)
    img.save(path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview")
    args = parser.parse_args()
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..",
                        "packaging", "android", "package", "res")
    files = {
        "drawable/ic_launcher_foreground.xml": vector_foreground(),
        "mipmap-anydpi-v26/ic_launcher.xml": ADAPTIVE,
        "mipmap-anydpi-v26/ic_launcher_round.xml": ADAPTIVE,
        "values/ic_launcher_colors.xml": COLORS_XML,
    }
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
    if args.preview:
        preview(args.preview)


if __name__ == "__main__":
    main()
